package com.smokeythebandicoot.deeperdark;

import com.smokeythebandicoot.deeperdark.config.ModConfig;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.Logger;
import zone.rong.mixinbooter.ILateMixinLoader;

import java.util.ArrayList;
import java.util.List;

@Mod(
        modid = DeeperDark.MODID,
        version = DeeperDark.MODVERSION,
        name = DeeperDark.MODNAME,
        useMetadata = true,
        dependencies = "after:extrautils2"
)
public class DeeperDark implements ILateMixinLoader {

    public static final String MODID = "deeperdarker";
    public static final String MODNAME = "Deeper Darker";
    public static final String MODVERSION = "1.0";
    public static final String MODDESCRIPTION = "A mod that allows modpack makers to customize the Deep Dark dimension.";
    public static final String MODAUTHOR = "SmokeyTheBandicoot";
    public static final String MODCREDITS = "";
    public static final String MODURL = "";
    public static final String MODLOGO = "assets/deeperdark/logo.png";

    public static Logger logger;
    @Instance(value = MODID)
    public static DeeperDark instance;

    @EventHandler
    public void onPreInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();

        // Set mod info
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = MODID;
        event.getModMetadata().credits = MODCREDITS;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(MODAUTHOR);
        event.getModMetadata().description = MODDESCRIPTION;
        event.getModMetadata().url = MODURL;
        event.getModMetadata().logoFile = MODLOGO;

    }

    @Override
    public List<String> getMixinConfigs() {
        List<String> configs = new ArrayList<>();
        configs.add("deeperdark.mixins.json");
        return configs;
    }

}